name: linter

on: [push]

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: repository
        uses: actions/checkout@v2
      - name: set node version 14
        uses: actions/setup-node@v2
        with:
            node-version: '14'
      - name: check node version
        run: node -v
      - name: install dependences
        run: npm install
      - name: linter
        run: make lint
