name: linter

on: push

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: make lint
        uses: actions/checkout@v2
        uses: actions/setup-node@v1
        run: make lint
