name: linter

on: [push]

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: repository
        uses: actions/checkout@v2
      - name: install dependences
        run: make install
      - name: linter
        run: make lint
