name: linter

on: [push]

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: repository
        uses: actions/checkout@v2

      - name: linter
        uses: .eslintrc.yml
        run: make lint
